import type { Metadata } from "next";
import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],  // Supports multiple character sets
  weight: ["800"], // Load only the necessary weights
  variable: "--font-bricolage", // Define a CSS variable for easy use
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={bricolageGrotesque.variable}
      >
        {children}
      </body>
    </html>
  );
}
